echo "Creating cpp compile tester"
#
# Break apart each filename.
# Wrap   #include "" around each
# Filter out the win32 file
#
TESTFILE=../../tests/cpp_compile_test.cpp

echo "/* test all header files for cpp compilation */">$TESTFILE
echo "/* this file is AUTOMATICALLY GENERATED by src/log4c/${0}  */">>$TESTFILE

for i in ${*}; do 
  j=$(expr match "${i}" '.*win32')
  if [[ "$j" == "0" ]]; then
    echo "#include \"../src/log4c/${i}\"" >>$TESTFILE
  fi
done

cat  >>$TESTFILE << EOF

#include <stdlib.h>

int main(int argc, char** argv)
{
  exit(0);
}
EOF


